services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
    ports:
      - "3307:3306"
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: ventas-api
    restart: always
    depends_on:
      - mysql
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network

  despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: despachos-api
    restart: always
    depends_on:
      - mysql
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    build:
      context: ./front_despacho
    container_name: frontend-app
    restart: always
    depends_on:
      - ventas
      - despachos
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge